baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "3DS Modding: Engineer's Handbook"
theme = 'hugo-book'

[params]
# (Optional, default light) Sets color theme: light, dark or auto.
# Theme 'auto' switches between dark and light modes based on browser/os preferences
BookTheme = 'dark'
Description = 'A comprehensive guide to modding 3DS games'
